"""Postgres access for the recipe dashboard. Plain psycopg, no ORM.

Connections are autocommit; the two writers that touch more than one table
wrap themselves in `conn.transaction()`.
"""

from datetime import date, datetime, timedelta

import psycopg
from psycopg.rows import dict_row

SCHEMA = """
CREATE TABLE IF NOT EXISTS recipes (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  source_url  TEXT,
  ingredients TEXT NOT NULL DEFAULT '',
  steps       TEXT NOT NULL DEFAULT '',
  rating      INTEGER,
  notes       TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe_tags (
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  tag       TEXT NOT NULL,
  PRIMARY KEY (recipe_id, tag)
);

-- A week's shortlist: which recipes we intend to cook, with no day attached.
-- `week` is the ISO date of that week's Monday.
CREATE TABLE IF NOT EXISTS plan (
  week      TEXT NOT NULL,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  PRIMARY KEY (week, recipe_id)
);

-- Things the household buys regardless of what is being cooked. They join
-- every week's kitchen check alongside the recipe ingredients.
CREATE TABLE IF NOT EXISTS staples (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line TEXT NOT NULL UNIQUE
);

-- "We already have this, do not buy it." One row per item marked in the
-- kitchen check; absence means it still needs buying. Keyed per week so last
-- week's answers do not silently carry over.
CREATE TABLE IF NOT EXISTS pantry (
  week     TEXT NOT NULL,
  item_key TEXT NOT NULL,
  PRIMARY KEY (week, item_key)
);

-- What aisle an ingredient lives in, learned once and reused forever.
-- Keyed by grocery.sort_key(line), so "1 lb ground beef" and "2 lbs ground
-- beef" share the one entry. Populated by the grocery-sort agent skill.
CREATE TABLE IF NOT EXISTS aisles (
  key   TEXT PRIMARY KEY,
  aisle TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recipe_tags_tag ON recipe_tags(tag);
"""


def connect() -> psycopg.Connection:
    """Reads PGHOST/PGUSER/PGPASSWORD/PGDATABASE from the environment."""
    return psycopg.connect(row_factory=dict_row, autocommit=True)


def init_schema(conn: psycopg.Connection) -> None:
    conn.execute(SCHEMA)


def _norm_tags(tags) -> list[str]:
    seen = {t.strip().lower() for t in tags or ()}
    return sorted(t for t in seen if t)


def _set_tags(conn: psycopg.Connection, recipe_id: int, tags) -> None:
    conn.execute("DELETE FROM recipe_tags WHERE recipe_id = %s", (recipe_id,))
    conn.cursor().executemany(
        "INSERT INTO recipe_tags (recipe_id, tag) VALUES (%s, %s)",
        [(recipe_id, t) for t in _norm_tags(tags)],
    )


def create_recipe(
    conn: psycopg.Connection,
    title: str,
    *,
    ingredients: str = "",
    steps: str = "",
    notes: str = "",
    source_url: str | None = None,
    tags=(),
) -> int:
    with conn.transaction():
        recipe_id = conn.execute(
            """INSERT INTO recipes (title, source_url, ingredients, steps, notes, created_at)
               VALUES (%s, %s, %s, %s, %s, %s) RETURNING id""",
            (title, source_url, ingredients, steps, notes, datetime.now().isoformat(timespec="seconds")),
        ).fetchone()["id"]
        _set_tags(conn, recipe_id, tags)
    return recipe_id


def get_recipe(conn: psycopg.Connection, recipe_id: int) -> dict | None:
    return conn.execute("SELECT * FROM recipes WHERE id = %s", (recipe_id,)).fetchone()


def get_tags(conn: psycopg.Connection, recipe_id: int) -> list[str]:
    rows = conn.execute(
        "SELECT tag FROM recipe_tags WHERE recipe_id = %s ORDER BY tag", (recipe_id,)
    )
    return [r["tag"] for r in rows]


def update_recipe(
    conn: psycopg.Connection,
    recipe_id: int,
    *,
    title: str,
    ingredients: str,
    steps: str,
    notes: str,
    source_url: str | None,
    tags,
) -> None:
    with conn.transaction():
        conn.execute(
            """UPDATE recipes
                  SET title = %s, ingredients = %s, steps = %s, notes = %s, source_url = %s
                WHERE id = %s""",
            (title, ingredients, steps, notes, source_url, recipe_id),
        )
        _set_tags(conn, recipe_id, tags)


def delete_recipe(conn: psycopg.Connection, recipe_id: int) -> None:
    conn.execute("DELETE FROM recipes WHERE id = %s", (recipe_id,))


_SORTS = {
    "newest": "r.created_at DESC, r.id DESC",
    "title": "lower(r.title)",
    "rating": "r.rating DESC NULLS LAST, lower(r.title)",
}


def list_recipes(
    conn: psycopg.Connection,
    *,
    q: str | None = None,
    tag: str | None = None,
    sort: str = "newest",
) -> list[dict]:
    where, params = [], []
    if q:
        where.append("r.title ILIKE %s")
        params.append(f"%{q}%")
    if tag:
        where.append("EXISTS (SELECT 1 FROM recipe_tags t WHERE t.recipe_id = r.id AND t.tag = %s)")
        params.append(tag.strip().lower())

    sql = f"""
        SELECT r.*
          FROM recipes r
         {'WHERE ' + ' AND '.join(where) if where else ''}
         ORDER BY {_SORTS.get(sort, _SORTS['newest'])}
    """
    rows = conn.execute(sql, params).fetchall()

    # Tags are joined in Python so their order is the plain ORDER BY tag below.
    by_recipe: dict[int, list[str]] = {}
    for r in conn.execute("SELECT recipe_id, tag FROM recipe_tags ORDER BY tag"):
        by_recipe.setdefault(r["recipe_id"], []).append(r["tag"])

    out = []
    for row in rows:
        rec = dict(row)
        rec["tags"] = ", ".join(by_recipe.get(rec["id"], ()))
        out.append(rec)
    return out


def all_tags(conn: psycopg.Connection) -> list[str]:
    return [r["tag"] for r in conn.execute("SELECT DISTINCT tag FROM recipe_tags ORDER BY tag")]


def set_rating(conn: psycopg.Connection, recipe_id: int, rating: int | None) -> None:
    if rating is not None and not 1 <= int(rating) <= 5:
        raise ValueError(f"rating must be 1-5 or None, got {rating!r}")
    conn.execute("UPDATE recipes SET rating = %s WHERE id = %s", (rating, recipe_id))


def week_start(d: date) -> date:
    return d - timedelta(days=d.weekday())


def get_plan(conn: psycopg.Connection, week: date) -> list[dict]:
    """The recipes shortlisted for that week, alphabetical."""
    return conn.execute(
        """SELECT r.* FROM plan p JOIN recipes r ON r.id = p.recipe_id
            WHERE p.week = %s
            ORDER BY lower(r.title)""",
        (week_start(week).isoformat(),),
    ).fetchall()


def add_to_plan(conn: psycopg.Connection, week: date, recipe_id: int) -> None:
    conn.execute(
        "INSERT INTO plan (week, recipe_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
        (week_start(week).isoformat(), recipe_id),
    )


def remove_from_plan(conn: psycopg.Connection, week: date, recipe_id: int) -> None:
    conn.execute(
        "DELETE FROM plan WHERE week = %s AND recipe_id = %s",
        (week_start(week).isoformat(), recipe_id),
    )


def get_aisles(conn: psycopg.Connection) -> dict[str, str]:
    """The whole learned key -> aisle map. It stays small: one row per
    distinct ingredient the household has ever planned."""
    return {r["key"]: r["aisle"] for r in conn.execute("SELECT key, aisle FROM aisles")}


def set_aisles(conn: psycopg.Connection, mapping: dict[str, str]) -> int:
    """Upsert learned aisles. Returns the number of rows written."""
    rows = [(k, v) for k, v in mapping.items() if k and v]
    conn.cursor().executemany(
        "INSERT INTO aisles (key, aisle) VALUES (%s, %s) "
        "ON CONFLICT(key) DO UPDATE SET aisle = excluded.aisle",
        rows,
    )
    return len(rows)


def get_staples(conn: psycopg.Connection) -> list[dict]:
    return conn.execute("SELECT id, line FROM staples ORDER BY line ").fetchall()


def add_staple(conn: psycopg.Connection, line: str) -> None:
    line = " ".join((line or "").split())
    if not line:
        raise ValueError("a staple needs a name")
    conn.execute("INSERT INTO staples (line) VALUES (%s) ON CONFLICT DO NOTHING", (line,))


def remove_staple(conn: psycopg.Connection, staple_id: int) -> None:
    conn.execute("DELETE FROM staples WHERE id = %s", (staple_id,))


def get_pantry(conn: psycopg.Connection, week: date) -> set[str]:
    """Item keys marked "we already have this" for that week."""
    rows = conn.execute(
        "SELECT item_key FROM pantry WHERE week = %s", (week_start(week).isoformat(),)
    )
    return {r["item_key"] for r in rows}


def set_pantry(conn: psycopg.Connection, week: date, item_key: str, have: bool) -> None:
    wk = week_start(week).isoformat()
    if have:
        conn.execute(
            "INSERT INTO pantry (week, item_key) VALUES (%s, %s) ON CONFLICT DO NOTHING",
            (wk, item_key),
        )
    else:
        conn.execute(
            "DELETE FROM pantry WHERE week = %s AND item_key = %s", (wk, item_key)
        )
